name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

env:
  MOPAC_VERSION: 23.2.2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Get MOPAC shared library
      run: |
        curl -OL https://github.com/openmopac/mopac/releases/download/v${{ env.MOPAC_VERSION }}/mopac-${{ env.MOPAC_VERSION }}-linux.tar.gz
        tar -xvzf mopac-${{ env.MOPAC_VERSION }}-linux.tar.gz
        mkdir src/mopactools/lib
        cp mopac-${{ env.MOPAC_VERSION }}-linux/lib/* src/mopactools/lib

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install ."

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/_build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
